//Information obtained from Flat UI Color - https://flatuicolors.com/

export const SunFlower = "#f1c40f"
export const Carrot = "#e67e22"
export const Alizarin = "#e74c3c"
export const Pumpkin = "#d35400"
export const Orange = "#f39c12"
export const Pomegranate = "#c0392b"
export const Emerald = "#2ecc71"
export const PeterRiver = "#3498db"
export const Turquoise = "#1abc9c"
export const Clouds = "#ecf0f1"
export const Silver = "#bdc3c7"
export const Abestos = "#7f8c8d"
export const BelizeHole = "#2980b9"
export const Nephritis ="#27ae60"
export const IosBlue = "#007AFF"
export const DarkGray= "#5C5C5C"
export const WetAsphalt = "#2c3e50"
export const MidNightBlue= "#2c3e50"
export const Amethyst = "#9b59b6"
export const Wisteria= "#8e44ad"